version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: ipos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Karkala1998?
      MYSQL_DATABASE: ipos_sa
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pKarkala1998?" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
  ipos-sa:
    build: .
    container_name: ipos-sa-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ipos_sa
      DB_USER: root
      DB_PASSWORD: Karkala1998?
    ports:
      - "8081:8081"
      - "5900:5900"
      - "6082:6082"
    stdin_open: true
    tty: true
volumes:
  mysql_data: