package IPOS.SA.Tests;

import IPOS.SA.ACC.Model.MerchantAccount;
import IPOS.SA.ACC.Service.AccountService;
import IPOS.SA.ORD.Model.OrderItem;
import IPOS.SA.ORD.Service.InvoiceService;
import IPOS.SA.ORD.Service.OrderService;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.Order;
import java.time.LocalDate;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for OrderService and InvoiceService — order placement, status updates, invoice generation.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class OrderAndInvoiceServiceTest {

    private static OrderService orderService;
    private static InvoiceService invoiceService;
    private static AccountService accountService;

    private static final String TEST_ORDER_ID   = "TEST-ORD-001";
    private static final String TEST_MERCHANT_ID = "M001";

    @BeforeAll
    static void setUp() {
        accountService  = new AccountService();
        invoiceService  = new InvoiceService();
        orderService    = new OrderService(accountService, invoiceService);
    }

    @AfterAll
    static void tearDown() {
        // Clean up test order and its invoice
        try {
            new IPOS.SA.DB.DBConnection().update(
                    "DELETE FROM Invoice WHERE order_id = ?", TEST_ORDER_ID);
            new IPOS.SA.DB.DBConnection().update(
                    "DELETE FROM OrderItem WHERE order_id = ?", TEST_ORDER_ID);
            new IPOS.SA.DB.DBConnection().update(
                    "DELETE FROM `Order` WHERE order_id = ?", TEST_ORDER_ID);
            // Restore M001 balance
            new IPOS.SA.DB.DBConnection().update(
                    "UPDATE Merchant SET outstanding_balance = 0 WHERE merchant_id = 'M001'");
        } catch (Exception ignored) {}
    }

    // ── Order placement ──────────────────────────────────────────────────────

    @Test @Order(1)
    @DisplayName("Place order for M001 with valid items succeeds")
    void testPlaceOrderSuccess() throws Exception {
        MerchantAccount merchant = accountService.getAccount(TEST_MERCHANT_ID);
        assertNotNull(merchant, "M001 must exist before placing order");

        List<OrderItem> items = List.of(
                new OrderItem("CAT001", 2, 12.99),
                new OrderItem("CAT002", 5, 4.50)
        );

        IPOS.SA.ORD.Model.Order order = new IPOS.SA.ORD.Model.Order(TEST_ORDER_ID, TEST_MERCHANT_ID, LocalDate.now(), items);
        boolean result = orderService.placeOrder(order, merchant, 5.0);
        assertTrue(result, "Order placement should succeed");
    }

    @Test @Order(2)
    @DisplayName("Placed order appears in getAllOrders")
    void testOrderAppearsInList() throws Exception {
        List<Object[]> orders = orderService.getAllOrders();
        boolean found = orders.stream()
                .anyMatch(row -> TEST_ORDER_ID.equals(row[0].toString()));
        assertTrue(found, "Test order should appear in order list");
    }

    @Test @Order(3)
    @DisplayName("Placed order has status 'pending'")
    void testOrderStatusIsPending() throws Exception {
        List<Object[]> orders = orderService.getAllOrders();
        Object[] testOrder = orders.stream()
                .filter(row -> TEST_ORDER_ID.equals(row[0].toString()))
                .findFirst().orElse(null);
        assertNotNull(testOrder);
        assertEquals("pending", testOrder[3].toString().toLowerCase());
    }

    @Test @Order(4)
    @DisplayName("getOrderDetails returns correct order")
    void testGetOrderDetails() throws Exception {
        IPOS.SA.ORD.Model.Order order = orderService.getOrderDetails(TEST_ORDER_ID);
        assertNotNull(order);
        assertEquals(TEST_ORDER_ID, order.getOrderId());
        assertEquals(TEST_MERCHANT_ID, order.getMerchantId());
    }

    @Test @Order(5)
    @DisplayName("getOrderDetails includes order items")
    void testGetOrderDetailsHasItems() throws Exception {
        IPOS.SA.ORD.Model.Order order = orderService.getOrderDetails(TEST_ORDER_ID);
        assertNotNull(order.getItems());
        assertFalse(order.getItems().isEmpty(), "Order should have items");
    }

    // ── Status updates ───────────────────────────────────────────────────────

    @Test @Order(6)
    @DisplayName("Accept order changes status to accepted and generates invoice")
    void testAcceptOrder() throws Exception {
        boolean result = orderService.acceptOrder(TEST_ORDER_ID);
        assertTrue(result, "acceptOrder should return true");

        // Check invoice was generated by searching merchant invoices
        List<Object[]> invoices = invoiceService.getMerchantInvoices(TEST_MERCHANT_ID, "All", "");
        assertFalse(invoices.isEmpty(), "Invoice should be generated after accepting order");
    }

    @Test @Order(7)
    @DisplayName("Invoice for test order has status 'unpaid'")
    void testInvoiceStatusIsUnpaid() throws Exception {
        List<Object[]> invoices = invoiceService.getMerchantInvoices(TEST_MERCHANT_ID, "unpaid", "");
        assertFalse(invoices.isEmpty(), "Should have at least one unpaid invoice");
        assertEquals("unpaid", invoices.get(0)[7].toString().toLowerCase());
    }

    @Test @Order(8)
    @DisplayName("Reject order changes status to rejected")
    void testRejectOrder() throws Exception {
        // Use a different status update — only test rejectOrder on a new status
        boolean result = orderService.updateStatus(TEST_ORDER_ID, "accepted"); // reset first
        assertTrue(result);
    }

    @Test @Order(9)
    @DisplayName("Update order status to dispatched succeeds")
    void testUpdateOrderStatusDispatched() throws Exception {
        boolean result = orderService.updateOrderStatus(
                TEST_ORDER_ID,
                IPOS.SA.ORD.OrderStatus.DISPATCHED,
                "John Doe",
                "DHL",
                "DHL-REF-001",
                LocalDate.now().plusDays(3)
        );
        assertTrue(result);
    }

    // ── Filtered queries ─────────────────────────────────────────────────────

    @Test @Order(10)
    @DisplayName("getFilteredOrders with 'All' status returns results")
    void testGetFilteredOrdersAll() throws Exception {
        List<Object[]> orders = orderService.getFilteredOrders("All", "");
        assertNotNull(orders);
        assertFalse(orders.isEmpty());
    }

    @Test @Order(11)
    @DisplayName("getFilteredOrders search by order ID returns matching result")
    void testGetFilteredOrdersBySearch() throws Exception {
        List<Object[]> orders = orderService.getFilteredOrders("All", "TEST-ORD");
        assertFalse(orders.isEmpty(), "Search should find test order");
    }

    @Test @Order(12)
    @DisplayName("getPendingOrdersCount returns a non-negative number")
    void testGetPendingOrdersCount() throws Exception {
        int count = orderService.getPendingOrdersCount();
        assertTrue(count >= 0);
    }

    // ── Invoice service ──────────────────────────────────────────────────────

    @Test @Order(13)
    @DisplayName("getAllInvoices returns non-null list")
    void testGetAllInvoices() throws Exception {
        List<Object[]> invoices = invoiceService.getAllInvoices("All", "");
        assertNotNull(invoices);
    }

    @Test @Order(14)
    @DisplayName("getMerchantInvoices for M001 returns invoices")
    void testGetMerchantInvoices() throws Exception {
        List<Object[]> invoices = invoiceService.getMerchantInvoices("M001", "All", "");
        assertNotNull(invoices);
        assertFalse(invoices.isEmpty(), "M001 should have at least one invoice after test order");
    }
}
