package IPOS.SA.RPT.UI;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Date;
import java.util.List;

import IPOS.SA.CAT.UI.Catalogue;
import IPOS.SA.RPT.Service.ReportService;
import IPOS.SA.ACC.UI.*;

// Creates a form to display the reports generated by the user
public class ReportForm extends JFrame {
    private final ReportService reportService;
    private final String fullname;
    private final String role;

    // UI Components
    private JPanel MainPanel;
    private JPanel ContentPanel;
    private JPanel NavPanel;
    private JPanel HeaderPanel;
    private JPanel CenterPanel;
    private JPanel FooterPanel;
    private JComboBox<String> reportTypeCombo;
    private JComboBox<String> merchantCombo;
    private JSpinner fromDateSpinner;
    private JSpinner toDateSpinner;
    private JTable reportTable;
    private JTextArea reportTextArea;
    private JTabbedPane tabbedPane;
    private JButton generateBtn;
    private JButton printBtn;
    private JLabel statusLabel;
    private JLabel headerLabel;
    private JLabel navIcon;
    private JButton logoutBtn;
    private JSeparator divider;

    public ReportForm(String fullname, String role) {
        this.reportService = new ReportService();
        this.fullname = fullname;
        this.role = role;

        setTitle("Report Viewer");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setContentPane(MainPanel);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

        initializeUI();

        setVisible(true);
    }

    // Method to call all the UI generation functionality
    private void initializeUI() {
        createHeaderPanel();
        createNavPanel();
        createCenterPanel();
        loadMerchants();
    }

    private void createHeaderPanel() {
        HeaderPanel.setLayout(new BoxLayout(HeaderPanel, BoxLayout.X_AXIS));
        HeaderPanel.setPreferredSize(new Dimension(1000, 54));
        HeaderPanel.setBackground(new Color(240, 252, 255));
        HeaderPanel.setBorder(BorderFactory.createEmptyBorder(0, 24, 0, 24));

        JPanel textPanel = new JPanel();
        textPanel.setLayout(new BoxLayout(textPanel, BoxLayout.Y_AXIS));
        textPanel.setOpaque(false);

        headerLabel = new JLabel("Report Generator");
        headerLabel.setForeground(Color.BLACK);
        headerLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));

        textPanel.add(headerLabel);
        HeaderPanel.add(textPanel);
    }

    private void createNavPanel() {
        NavPanel.setLayout(new BoxLayout(NavPanel, BoxLayout.Y_AXIS));
        NavPanel.setBackground(new Color(14, 37, 48));
        NavPanel.setBorder(BorderFactory.createEmptyBorder(20, 16, 20, 16));
        NavPanel.setPreferredSize(new Dimension(220, 0));

        ImageIcon Icon = new ImageIcon(new ImageIcon("data/Logo.png")
                .getImage().getScaledInstance(80, 60, Image.SCALE_SMOOTH));
        navIcon = new JLabel(Icon);

        NavPanel.add(navIcon);
        NavPanel.add(Box.createVerticalStrut(16));

        NavPanel.add(buildNavButton("Overview", true));
        NavPanel.add(Box.createVerticalStrut(4));
        NavPanel.add(buildNavButton("Catalogue", false));
        NavPanel.add(Box.createVerticalStrut(4));
        NavPanel.add(buildNavButton("Orders", false));
        NavPanel.add(Box.createVerticalStrut(4));

        addExpandableNavItem(NavPanel, "Merchants", new String[]{
                "View Merchant Orders", "View Merchant Invoices"
        });

        addExpandableNavItem(NavPanel, "Accounts", new String[]{
                "View All Merchants", "Create Merchant Account", "Manage Merchant Accounts", "Commercial Applications"
        });

        addExpandableNavItem(NavPanel, "Staff", new String[]{
                "View All Staff", "Create Staff Account", "Manage Staff Account",
        });

        NavPanel.add(buildNavButton("Reports", true));
        NavPanel.add(Box.createVerticalStrut(4));
        NavPanel.add(buildNavButton("Settings", false));
        NavPanel.add(Box.createVerticalStrut(4));

        divider = new JSeparator();
        divider.setForeground(Color.WHITE);
        divider.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1));
        NavPanel.add(divider);
        NavPanel.add(Box.createVerticalGlue());

        logoutBtn = new JButton("→  Log out");
        logoutBtn.setFont(new Font("Segoe UI", Font.BOLD, 13));
        logoutBtn.setForeground(new Color(200, 80, 80));
        logoutBtn.setBackground(new Color(14, 37, 48));
        logoutBtn.setBorderPainted(false);
        logoutBtn.setFocusPainted(false);
        logoutBtn.setAlignmentX(Component.LEFT_ALIGNMENT);
        logoutBtn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 36));
        logoutBtn.setHorizontalAlignment(SwingConstants.LEFT);
        logoutBtn.addActionListener(e -> handleLogout());
        NavPanel.add(logoutBtn);
    }

    private void createCenterPanel() {
        ContentPanel.setLayout(new BorderLayout());
        ContentPanel.setBackground(new Color(245, 247, 250));

        // Top filter panel
        JPanel filterPanel = createFilterPanel();
        ContentPanel.add(filterPanel, BorderLayout.NORTH);

        // Center tabbed pane for report display
        tabbedPane = new JTabbedPane();

        // Table view
        reportTable = new JTable();
        reportTable.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        reportTable.setRowHeight(25);
        JScrollPane tableScroll = new JScrollPane(reportTable);
        tabbedPane.addTab("Table View", tableScroll);

        // Text view (for formatted reports)
        reportTextArea = new JTextArea();
        reportTextArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        reportTextArea.setEditable(false);
        JScrollPane textScroll = new JScrollPane(reportTextArea);
        tabbedPane.addTab("Formatted View", textScroll);

        ContentPanel.add(tabbedPane, BorderLayout.CENTER);

        // Bottom button panel
        JPanel buttonPanel = createButtonPanel();
        ContentPanel.add(buttonPanel, BorderLayout.SOUTH);
    }

    private JPanel createFilterPanel() {
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 10));
        panel.setBackground(new Color(17, 24, 39));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 16, 10, 16));

        // Report type - ADD Low Stock Report
        panel.add(new JLabel("Report Type:"));
        reportTypeCombo = new JComboBox<>(new String[]{
                "Low Stock Report",
                "Turnover Report",
                "Merchant Orders",
                "Merchant Activity",
                "Invoices by Merchant",
                "All Invoices",
                "Stock Turnover"
        });
        reportTypeCombo.setPreferredSize(new Dimension(180, 30));
        reportTypeCombo.addActionListener(e -> updateMerchantDropdown());
        panel.add(reportTypeCombo);

        // Merchant selector
        panel.add(new JLabel("Merchant:"));
        merchantCombo = new JComboBox<>();
        merchantCombo.setPreferredSize(new Dimension(200, 30));
        panel.add(merchantCombo);

        // Date range
        panel.add(new JLabel("From:"));
        fromDateSpinner = new JSpinner(new SpinnerDateModel());
        JSpinner.DateEditor fromEditor = new JSpinner.DateEditor(fromDateSpinner, "yyyy-MM-dd");
        fromDateSpinner.setEditor(fromEditor);
        fromDateSpinner.setValue(new Date(System.currentTimeMillis() - 30L * 24 * 60 * 60 * 1000));
        panel.add(fromDateSpinner);

        panel.add(new JLabel("To:"));
        toDateSpinner = new JSpinner(new SpinnerDateModel());
        JSpinner.DateEditor toEditor = new JSpinner.DateEditor(toDateSpinner, "yyyy-MM-dd");
        toDateSpinner.setEditor(toEditor);
        toDateSpinner.setValue(new Date());
        panel.add(toDateSpinner);

        return panel;
    }

    private void loadMerchants() {
        try {
            List<String[]> merchants = reportService.getMerchantList();
            merchantCombo.removeAllItems();
            merchantCombo.addItem("All Merchants");

            for (String[] merchant : merchants) {
                merchantCombo.addItem(merchant[0] + " - " + merchant[1]);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateMerchantDropdown() {
        String selectedReport = (String) reportTypeCombo.getSelectedItem();
        boolean needsMerchant = selectedReport.equals("Merchant Orders") ||
                selectedReport.equals("Merchant Activity") ||
                selectedReport.equals("Invoices by Merchant");
        merchantCombo.setEnabled(needsMerchant);
    }

    private JPanel createButtonPanel() {
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 10));
        panel.setBackground(new Color(17, 24, 39));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 12, 10, 12));

        generateBtn = new JButton("Generate Report");
        styleButton(generateBtn);
        generateBtn.addActionListener(e -> generateReport());
        panel.add(generateBtn);

        printBtn = new JButton("Print");
        styleButton(printBtn);
        printBtn.addActionListener(e -> printReport());
        panel.add(printBtn);

        statusLabel = new JLabel("Ready");
        statusLabel.setForeground(Color.WHITE);
        panel.add(statusLabel);

        return panel;
    }

    private void generateReport() {
        String reportType = (String) reportTypeCombo.getSelectedItem();
        Date fromDate = (Date) fromDateSpinner.getValue();
        Date toDate = (Date) toDateSpinner.getValue();
        String merchantSelection = (String) merchantCombo.getSelectedItem();

        try {
            statusLabel.setText("Generating report...");

            switch (reportType) {
                case "Low Stock Report":
                    generateLowStockReport();
                    break;
                case "Turnover Report":
                    generateTurnoverReport(fromDate, toDate);
                    break;
                case "Merchant Orders":
                    String merchantId = merchantSelection.split(" - ")[0];
                    generateMerchantOrdersReport(merchantId, fromDate, toDate);
                    break;
                case "Merchant Activity":
                    merchantId = merchantSelection.split(" - ")[0];
                    generateMerchantActivityReport(merchantId, fromDate, toDate);
                    break;
                case "Invoices by Merchant":
                    merchantId = merchantSelection.split(" - ")[0];
                    generateInvoicesByMerchantReport(merchantId, fromDate, toDate);
                    break;
                case "All Invoices":
                    generateAllInvoicesReport(fromDate, toDate);
                    break;
                case "Stock Turnover":
                    generateStockTurnoverReport(fromDate, toDate);
                    break;
            }

            statusLabel.setText("Report generated successfully");
            tabbedPane.setSelectedIndex(0);
        } catch (Exception e) {
            statusLabel.setText("Error: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error generating report: " + e.getMessage());
        }
    }

    private void generateLowStockReport() throws Exception {
        List<String[]> data = reportService.getLowStockReport();
        if (data.isEmpty()) {
            data.add(new String[]{"No low stock items found", "", "", "", "", ""});
        }
        updateTableWithData(data, new String[]{"Item ID", "Description", "Package", "Unit", "Stock", "Min Level"});
    }

    private void generateTurnoverReport(Date fromDate, Date toDate) throws Exception {
        List<String[]> data = reportService.getTurnoverReport(fromDate, toDate);
        if (data.isEmpty()) {
            data.add(new String[]{"No data found for this period", "", "", ""});
        }
        updateTableWithData(data, new String[]{"Period", "Orders", "Items Sold", "Revenue (£)"});
    }

    private void generateMerchantOrdersReport(String merchantId, Date fromDate, Date toDate) throws Exception {
        List<String[]> data = reportService.getMerchantOrdersReport(merchantId, fromDate, toDate);
        if (data.isEmpty()) {
            data.add(new String[]{"No orders found for this merchant", "", "", "", ""});
        }
        updateTableWithData(data, new String[]{"Order ID", "Date", "Amount (£)", "Dispatched", "Payment Status"});
    }

    private void generateMerchantActivityReport(String merchantId, Date fromDate, Date toDate) throws Exception {
        String reportText = reportService.getMerchantActivityReport(merchantId, fromDate, toDate);
        reportTextArea.setText(reportText);
        tabbedPane.setSelectedIndex(1);
    }

    private void generateInvoicesByMerchantReport(String merchantId, Date fromDate, Date toDate) throws Exception {
        List<String[]> data = reportService.getInvoicesByMerchant(merchantId, fromDate, toDate);
        if (data.isEmpty()) {
            data.add(new String[]{"No invoices found for this merchant", "", "", "", "", "", ""});
        }
        updateTableWithData(data, new String[]{"Invoice ID", "Date", "Due Date", "Order ID", "Total (£)", "Paid (£)", "Status"});
    }

    private void generateAllInvoicesReport(Date fromDate, Date toDate) throws Exception {
        List<String[]> data = reportService.getAllInvoicesReport(fromDate, toDate);
        if (data.isEmpty()) {
            data.add(new String[]{"No invoices found", "", "", "", "", "", "", ""});
        }
        updateTableWithData(data, new String[]{"Invoice ID", "Merchant", "Date", "Due Date", "Order ID", "Total (£)", "Paid (£)", "Status"});
    }

    private void generateStockTurnoverReport(Date fromDate, Date toDate) throws Exception {
        List<String[]> data = reportService.getStockTurnoverReport(fromDate, toDate);
        if (data.isEmpty()) {
            data.add(new String[]{"No stock movement found", "", "", "", "", ""});
        }
        updateTableWithData(data, new String[]{"Item ID", "Description", "Sold", "Received", "Net Change", "Revenue (£)"});
    }

    private void updateTableWithData(List<String[]> data, String[] columns) {
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (String[] row : data) {
            model.addRow(row);
        }

        reportTable.setModel(model);

        // Auto-size columns
        for (int i = 0; i < reportTable.getColumnCount(); i++) {
            reportTable.getColumnModel().getColumn(i).setPreferredWidth(100);
        }

        tabbedPane.setSelectedIndex(0);
    }

    private void printReport() {
        try {
            boolean complete = reportTextArea.print();
            if (complete) {
                statusLabel.setText("Print job sent successfully");
            } else {
                statusLabel.setText("Printing cancelled");
            }
        } catch (Exception e) {
            statusLabel.setText("Print error: " + e.getMessage());
        }
    }

    private void styleButton(JButton btn) {
        btn.setBackground(new Color(30, 70, 90));
        btn.setForeground(Color.WHITE);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        btn.setPreferredSize(new Dimension(100, 32));
    }

    private void addExpandableNavItem(JPanel nav, String label, String[] subItems) {
        JButton mainBtn = new JButton(label);
        mainBtn.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        mainBtn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 36));
        mainBtn.setAlignmentX(Component.LEFT_ALIGNMENT);
        mainBtn.setHorizontalAlignment(SwingConstants.LEFT);
        mainBtn.setFocusPainted(false);
        mainBtn.setBorderPainted(false);
        mainBtn.setBackground(new Color(14, 37, 48));
        mainBtn.setForeground(new Color(160, 190, 210));

        JPanel subPanel = new JPanel();
        subPanel.setLayout(new BoxLayout(subPanel, BoxLayout.Y_AXIS));
        subPanel.setBackground(new Color(10, 28, 38));
        subPanel.setVisible(false);

        for (String sub : subItems) {
            JButton subBtn = new JButton("    › " + sub);
            subBtn.setFont(new Font("Segoe UI", Font.PLAIN, 12));
            subBtn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
            subBtn.setAlignmentX(Component.LEFT_ALIGNMENT);
            subBtn.setHorizontalAlignment(SwingConstants.LEFT);
            subBtn.setFocusPainted(false);
            subBtn.setBorderPainted(false);
            subBtn.setBackground(new Color(10, 28, 38));
            subBtn.setForeground(new Color(120, 160, 185));

            subBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    subBtn.setForeground(Color.WHITE);
                    subBtn.setBackground(new Color(20, 50, 65));
                }
                public void mouseExited(java.awt.event.MouseEvent e) {
                    subBtn.setForeground(new Color(120, 160, 185));
                    subBtn.setBackground(new Color(10, 28, 38));
                }
            });

            subBtn.addActionListener(e -> {
                switch (sub) {
                    case "View All Merchants":
                        dispose();
                        new MerchantList(fullname, role);
                        break;
                    case "Create Merchant Account":
                        dispose();
                        new AccountManagement(fullname, role, "CREATE");
                        break;
                    case "Manage Merchant Accounts":
                        dispose();
                        new AccountManagement(fullname, role, "MANAGE");
                        break;
                    case "View All Staff":
                        dispose();
                        new StaffList(fullname, role);
                        break;
                    case "Create Staff Account":
                        dispose();
                        new StaffAccountManagement(fullname, role, "CREATE");
                        break;
                    case "Manage Staff Account":
                        dispose();
                        new StaffAccountManagement(fullname, role, "MANAGE");
                        break;
                    default:
                        JOptionPane.showMessageDialog(ReportForm.this, sub + " — coming soon.");
                        break;
                }
            });
            subPanel.add(subBtn);
            subPanel.add(Box.createVerticalStrut(2));
        }

        mainBtn.addActionListener(e -> {
            boolean showing = subPanel.isVisible();
            subPanel.setVisible(!showing);
            mainBtn.setForeground(showing ? new Color(160, 190, 210) : Color.WHITE);
            mainBtn.setBackground(showing ? new Color(14, 37, 48) : new Color(20, 45, 60));
            nav.revalidate();
            nav.repaint();
        });

        nav.add(mainBtn);
        nav.add(subPanel);
        nav.add(Box.createVerticalStrut(4));
    }

    private JButton buildNavButton(String label, boolean active) {
        JButton btn = new JButton(label);
        btn.setFont(new Font("Segoe UI", active ? Font.BOLD : Font.PLAIN, 13));
        btn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 36));
        btn.setAlignmentX(Component.LEFT_ALIGNMENT);
        btn.setHorizontalAlignment(SwingConstants.LEFT);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setBackground(active ? new Color(30, 70, 90) : new Color(14, 37, 48));
        btn.setForeground(active ? Color.WHITE : new Color(160, 190, 210));

        btn.addActionListener(e -> {
            dispose();
            switch (label) {
                case "Catalogue":
                    new Catalogue(fullname, role);
                    break;
                case "Overview":
                    new AdminDashboard(fullname, role);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, label + " — coming soon.");
                    break;
            }
        });

        return btn;
    }

    private void handleLogout() {
        dispose();
        new LoginForm();
    }
}